appear_input_dim: 1904
motion_input_dim: 1392
background_feature_dim: 880
encoder_output_dim: 1280
appear_feature_dim: 1024
motion_feature_dim: 512
temporature: 0.5
num_cluster: 2
gaussian_len: 70
gaussian_sigma: 15
segment_len: 16
batch_size: 256
removeMotionBranch: false
removeClusterHead: false
augmentMotion: false
train_dataset_path: data/Avenue/Avenue_train.npy
test_dataset_path: data/Avenue/Avenue_test.npy
test_mask_dir: data/Avenue/test_frame_mask/
MB_model_path: data/Avenue/saved_models/Avenue_MB.ckpt
encoder_model_path: data/Avenue/saved_models/Avenue_encoder.ckpt
decoder_model_path: data/Avenue/saved_models/Avenue_decoder.ckpt
augment_motion_path: /data/ssy/code/VAD_DC/data/Avenue/Avenue_augment_motion_scores.npy