appear_input_dim: 2614
motion_input_dim: 2102
background_feature_dim: 1590
encoder_output_dim: 1280
appear_feature_dim: 1024
motion_feature_dim: 512
temporature: 0.5
num_cluster: 4
gaussian_len: 80
gaussian_sigma: 50
segment_len: 16
removeMotionBranch: false
augmentMotion: false
train_dataset_path: data/mixture/shanghaitech/train_mix_10+12.npy
test_dataset_path: data/mixture/shanghaitech/test_mix_10+12.npy
test_mask_dir: data/mixture/shanghaitech/test_frame_mask/
MB_model_path: data/mixture/shanghaitech/saved_models/10+12_MB.ckpt
encoder_model_path: data/mixture/shanghaitech/saved_models/10+12_encoder.ckpt
decoder_model_path: data/mixture/shanghaitech/saved_models/10+12_decoder.ckpt