appear_input_dim: 2614
motion_input_dim: 2102
background_feature_dim: 1590
encoder_output_dim: 1280
appear_feature_dim: 1024
motion_feature_dim: 512
temporature: 0.5
num_cluster: 7
gaussian_len: 78
gaussian_sigma: 30
segment_len: 16
removeMotionBranch: false
augmentMotion: false
train_dataset_path: data/mixture/shanghaitech/train_mix_04+08.npy
test_dataset_path: data/mixture/shanghaitech/test_mix_04+08.npy
test_mask_dir: data/mixture/shanghaitech/test_frame_mask/
MB_model_path: data/mixture/shanghaitech/saved_models/04+08_MB.ckpt
encoder_model_path: data/mixture/shanghaitech/saved_models/04+08_encoder.ckpt
decoder_model_path: data/mixture/shanghaitech/saved_models/04+08_decoder.ckpt