appear_input_dim: 2614
motion_input_dim: 2102
background_feature_dim: 1590
encoder_output_dim: 1280
appear_feature_dim: 1024
motion_feature_dim: 512
temporature: 0.5
num_cluster: 23
gaussian_len: 78
gaussian_sigma: 30
segment_len: 16
batch_size: 256
removeMotionBranch: false
removeClusterHead: false
augmentMotion: false
train_dataset_path: data/SHT/SHT_train.npy
test_dataset_path: data/SHT/SHT_test.npy
test_mask_dir: data/SHT/test_frame_mask/
MB_model_path: data/SHT/saved_models/ShanghaiTech_MB.ckpt
encoder_model_path: data/SHT/saved_models/ShanghaiTech_encoder.ckpt
decoder_model_path: data/SHT/saved_models/ShanghaiTech_decoder.ckpt
augment_motion_path: /data/ssy/code/VAD_DC/data/SHT/ShanghaiTech_augment_motion_scores.npy