appear_input_dim: 1354
motion_input_dim: 842
background_feature_dim: 330
encoder_output_dim: 1280
appear_feature_dim: 1024
motion_feature_dim: 512
temporature: 0.5
num_cluster: 1
gaussian_len: 60
gaussian_sigma: 6
segment_len: 16
batch_size: 128
removeMotionBranch: true
removeClusterHead: true
augmentMotion: false
train_dataset_path: data/UCSD/UCSD_train.npy
test_dataset_path: data/UCSD/UCSD_test.npy
test_mask_dir: data/UCSD/test_frame_mask/
MB_model_path: data/UCSD/saved_models/Ped2_MB.ckpt
encoder_model_path: data/UCSD/saved_models/Ped2_encoder.ckpt
decoder_model_path: data/UCSD/saved_models/Ped2_decoder.ckpt